services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: always
    volumes:
      - searxng_config:/etc/searxng
      - searxng_data:/var/cache/searxng
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`search.tail.${DOMAIN_NAME}`)"
      - "traefik.http.routers.searxng.entrypoints=websecure"
      - "Traefik.http.routers.searxng.service=searxng"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080" # SearxNG default port

networks:
  traefik_proxy:
    external: true

volumes:
  searxng_config:
  searxng_data: