apiVersion: v1
kind: Namespace
metadata:
  name: homelab-pvr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvr-media-library
  namespace: homelab-pvr
  labels:
    type: pvr-media-library
spec:
  storageClassName: local-path
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/media-library
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvr-media-library-pvc
  namespace: homelab-pvr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: pvr-media-library
