apiVersion: v1
kind: Namespace
metadata:
  name: homelab-pvr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvr-media-library
  namespace: homelab-pvr
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/media-library